name: Unfollow Non-Followers

on:
  schedule:
    # Runs at 12:00 AM every day
    - cron: '0 0 * * *'

jobs:
  unfollow_non_followers:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Unfollow users who don't follow back
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          import requests

          def get_github_data(url, headers):
              response = requests.get(url, headers=headers)
              response.raise_for_status()
              return response.json()

          headers = {"Authorization": f"token {GH_TOKEN}"}
          
          # Get list of users you follow
          following_url = "https://api.github.com/user/following"
          following = [user['login'] for user in get_github_data(following_url, headers)]
          
          # Get list of your followers
          followers_url = "https://api.github.com/user/followers"
          followers = [user['login'] for user in get_github_data(followers_url, headers)]
          
          # Find users you follow who don't follow you back
          non_followers = set(following) - set(followers)
          
          for user in non_followers:
              unfollow_url = f"https://api.github.com/user/following/{user}"
              unfollow_response = requests.delete(unfollow_url, headers=headers)
              if unfollow_response.status_code == 204:
                  print(f"Unfollowed {user}")
              else:
                  print(f"Failed to unfollow {user}: {unfollow_response.status_code}")
